[project]
name = "qn-exp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "polars>=1.33.1",
    "prettytable>=3.16.0",
    "sequence>=0.8.1",
    "typer>=0.19.2",
]
